[placeholders]
nightly = { prompt = "Use nightly features?", choices = ["No", "Yes"], default = "No", type = "string" }

[conditional.'nightly == "No"']
ignore = ["rust-toolchain"]

[conditional.'nightly == "Yes"']
ignore = ["rust-toolchain.toml"]
